import { execFileSync } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { compileCapsule, renderCapsule } from "./context/compile.js";
import type { Budget, Capabilities, TaskRequest, UnitResult } from "./contracts/types.js";
import { sha256 } from "./contracts/identity.js";
import { Controller } from "./controller/controller.js";
import { createHandle, markVerified } from "./environment/handles.js";
import { defaultRegistry } from "./recipes/registry.js";
import { compileRecipe } from "./recipes/compile.js";
import { createClosedWorker } from "./worker/pi-adapter.js";
import { Type } from "typebox";

const root=resolve(import.meta.dirname,"..");
const allRecipes=["project.inspect","nix.enter","uv.sync_locked","python.identity","python.imports","tool.launch","check.run","environment.verify_fresh","loader.run"];
const caps:Capabilities={tools:["context_read","context_search","exec_action","episode_return"],recipes:allRecipes,allowTaskEnvironmentCreate:true,allowLockedSync:true,allowPackageDownloads:true,allowNixRealization:true,allowDirectLoader:true,allowFhsEntry:true,allowScratchRecipeProposal:false,allowSourceEdits:false,allowLockUpdates:false,allowHostConfigurationChanges:false,allowExternalPublication:false};
const budget:Budget={wallMs:900000,commandMsTotal:600000,perCommandMs:180000,maxModelRequests:16,maxToolActions:32,evidenceBytes:64*1024*1024,reportReserveMs:60000,reportReserveRequests:2,maxOutputTokensPerRequest:4000,estimatedInputTokenCeiling:12000,maxEstimatedCost:null};
function request(retry:"none"|"bounded_adaptive"):TaskRequest{return {schemaVersion:1,clientRequestId:`demo-${retry}`,taskId:null,parentEpisodeId:null,kind:"environment_recovery",mode:"adaptive",goal:"Create a locked uv environment in a real FHS wrapper, verify workspace source origin, launch tools, and report the deliberate source diagnostic",acceptanceUnit:{id:"fixture-environment",description:"FHS/uv environment operational against the fixture workspace"},fixedDecisions:[{id:"fixed-source",statement:"Do not edit source or locks",rationale:"environment recovery ends at semantic diagnostics",invalidatedBy:[]}],openLocalChoices:["registered FHS or explicit-loader route"],nonGoals:["semantic source repair","lock update","host configuration"],authoritySources:[{id:"local-demo-grant",issuer:"operator",reference:"CAPSULE_TRUSTED_LOCAL=1",scope:"disposable integration fixture only",supersedes:[]}],workspace:{projectRoot:root,executionRoot:root,sourceRoots:[join(root,"tests/fixtures/fhs-project/src")],readableRoots:[root],scratchRoot:join(root,".capsule-demo"),protectedPaths:["flake.lock","tests/fixtures/fhs-project/uv.lock","tests/fixtures/fhs-project/src"],excludedLargeDataRoots:[],sourceBinding:"workspace",expectedImports:[{module:"capsule_fixture",expectedOriginRoot:join(root,"tests/fixtures/fhs-project/src")}],executionTrust:"trusted-local",requiresHardIsolation:false},capabilities:caps,retry:{mode:retry,maxRecoveryAttempts:retry==="none"?0:3,allowedFailureClasses:["generic_loader","wrong_source_origin"],stopFailureClasses:["source_diagnostic","lock_mismatch"],requireNewEvidenceOrChangedAction:true},budget,evidenceRefs:[],criteria:[{id:"fresh-origin",unitId:"fixture-environment",description:"fresh process imports workspace",kind:"import_origin",verifierId:"origin-v1",arguments:{},required:true,requiresFreshExecution:true}],report:{profile:"environment",requiredFieldIds:["env.entry_recipe","env.lock_identities","env.import_origins","env.tool_launches","env.check_results","env.fresh_process","env.protected_changes","env.handle"],requiredCriterionIds:["fresh-origin"],narrativeMaxChars:8000,requireContraryEvidence:true,requireCoverage:true},returnTriggers:["genuine source diagnostic","permission boundary"]} as TaskRequest}
async function hashes(paths:string[]){return Object.fromEntries(await Promise.all(paths.map(async p=>[p,sha256(await readFile(p))])))}
const receiptView=(r:any)=>({id:r.id,recipe:r.recipeId,argv:r.argv,cwd:r.cwd,environmentHandleId:r.environmentHandleId,exitCode:r.exitCode,signal:r.signal,cancelled:r.cancelled,stdout:r.stdout,stderr:r.stderr});
async function demo(){
 if(process.env.CAPSULE_TRUSTED_LOCAL!=="1")throw new Error("trusted-local execution disabled; set CAPSULE_TRUSTED_LOCAL=1 after reviewing the fixture");
 const registry=defaultRegistry(),fixture=join(root,"tests/fixtures/fhs-project"),source=join(fixture,"src"),old=join(root,"tests/fixtures/old-source"),runRoot=join(root,"demo-results",new Date().toISOString().replaceAll(":","-"));await mkdir(runRoot,{recursive:true});
 const protectedPaths=[join(root,"flake.lock"),join(fixture,"uv.lock"),join(fixture,"pyproject.toml"),join(source,"capsule_fixture/__init__.py"),join(source,"capsule_fixture/broken.py")],before=await hashes(protectedPaths);const snapshot={id:"demo-snapshot",digest:sha256(JSON.stringify(before))};
 const capsule=compileCapsule(request("bounded_adaptive"),{id:"trusted-local-demo-policy",capabilities:caps,budget},snapshot,registry.digests());const controller=new Controller(capsule,join(runRoot,"state"));await controller.init();
 const action=async(id:string,recipeId:string,target:string,args:string[],env:Record<string,string>={},retryOf:string|null=null,failureClass?:string)=>{const recipe=registry.get(recipeId);const spec=compileRecipe(recipe,{projectRoot:root,installable:root,target,args,innerEnv:env});return controller.action(id,recipe,{...spec,timeoutMs:180000,externalEffectsAccounting:recipeId.startsWith("nix")||recipe.wrapperKind==="fhs"?"incomplete":"complete_for_declared_scope"},{unitId:"fixture-environment",retryOf,failureClass})};
 const taskEnv=join(runRoot,"uv-environment"),cache=join(runRoot,"uv-cache");
 const sync=await action("sync","uv.sync_locked","/bin/bash",["-euo","pipefail","-c",`cd "$1"; UV_PROJECT_ENVIRONMENT="$2" UV_CACHE_DIR="$3" uv sync --locked --no-install-project --python python3 --no-python-downloads`,"sync",fixture,taskEnv,cache]);
 const wrong=await action("origin-wrong","python.imports","/bin/bash",["-c",`"$1/bin/python" -c 'import capsule_fixture; print(capsule_fixture.__file__)'`,"origin",taskEnv],{PYTHONPATH:old});
 const fresh=await action("origin-fresh","environment.verify_fresh","/bin/bash",["-euo","pipefail","-c",`"$1/bin/python" -c 'import capsule_fixture,pathlib,os; actual=pathlib.Path(capsule_fixture.__file__).resolve(); expected=pathlib.Path(os.environ["EXPECTED_INIT"]).resolve(); print(actual); print(expected); assert actual == expected'`,"verify",taskEnv],{PYTHONPATH:source,EXPECTED_INIT:`${source}/capsule_fixture/__init__.py`},wrong.id,"wrong_source_origin");
 const tool=await action("tool-launch","tool.launch","/bin/bash",["-c","ruff --version; basedpyright --version"]);
 const check=await action("source-check","check.run","/bin/bash",["-c",`cd "$1"; basedpyright src`,"check",fixture],{PYTHONPATH:source});
 const generic=execFileSync("nix",["--extra-experimental-features","nix-command flakes","build","--no-link","--print-out-paths",`${root}#generic-checker`],{encoding:"utf8"}).trim();const glibc=execFileSync("nix",["--extra-experimental-features","nix-command flakes","build","--no-link","--print-out-paths",`${root}#loader-runtime`],{encoding:"utf8"}).trim();
 const direct=await action("generic-direct","project.inspect",`${generic}/bin/generic-checker`,[]);const loaderRecipe=registry.get("loader.run");const loaderSpec=compileRecipe(loaderRecipe,{projectRoot:root,target:`${generic}/bin/generic-checker`,args:[],loader:`${glibc}/lib/ld-linux-x86-64.so.2`,libraryPath:`${glibc}/lib`});const loader=await controller.action("generic-loader",loaderRecipe,{...loaderSpec,timeoutMs:30000},{unitId:"fixture-environment",retryOf:direct.id,failureClass:"generic_loader"});
 const after=await hashes(protectedPaths),unchanged=JSON.stringify(before)===JSON.stringify(after);const origin=`${source}/capsule_fixture/__init__.py`;const handle=markVerified(createHandle({taskId:capsule.taskId,capsuleDigest:capsule.digest,recipeId:"environment.verify_fresh",recipeDigest:registry.get("environment.verify_fresh").digest,wrapperKind:"fhs",sourceBinding:"workspace",projectRoot:root,sourceSnapshotId:snapshot.id,requiredConfigDigests:Object.fromEntries(protectedPaths.map(p=>[p,after[p]])),materializationRoot:taskEnv,entryParameters:{installable:root,sourceBindingInsideFinalWrapper:{PYTHONPATH:source}},observedPython:{executable:`${taskEnv}/bin/python`,version:"observed in receipt"},observedImports:[{module:"capsule_fixture",origin,distributionVersion:"0.1.0"}],observedTools:[{name:"ruff",version:"receipt",executable:"ruff",launcher:"fhs"},{name:"basedpyright",version:"receipt",executable:"basedpyright",launcher:"fhs"}],observedStorePaths:[generic,glibc],validForCriterionIds:[],invalidationConditions:["flake/uv/config digest changes","materialization missing","fresh origin or tool probe fails"]}),fresh.id,["fresh-origin"]);
 const replayRecipe=registry.get("environment.verify_fresh"),replayCompiled=compileRecipe(replayRecipe,{projectRoot:root,installable:root,target:"/bin/bash",args:["-c",`"$1/bin/python" -c 'import capsule_fixture,pathlib,os; assert pathlib.Path(capsule_fixture.__file__).resolve() == pathlib.Path(os.environ["EXPECTED_INIT"]).resolve(); print(capsule_fixture.__file__)'`,"replay",taskEnv],innerEnv:{PYTHONPATH:source,EXPECTED_INIT:origin}});const replay=await controller.action("handle-replay",replayRecipe,{...replayCompiled,timeoutMs:180000,externalEffectsAccounting:"incomplete"},{unitId:"fixture-environment",handleId:handle.id});
 const unit:UnitResult={unitId:"fixture-environment",executionState:"completed",verification:"fail",acceptance:"pending",criterionIds:["fresh-origin"],evidenceRefs:[],explanation:`Environment and loader operational; source check correctly failed with exit ${check.exitCode}.`};const draft:any={schemaVersion:1,taskId:capsule.taskId,episodeId:controller.episodeId,capsuleDigest:capsule.digest,requestedDisposition:"needs_decision",summary:"Real FHS and locked uv setup succeeded; stale source origin was detected and corrected inside the wrapper. Explicit loader succeeded. basedpyright launched and reported the deliberate source error; no source repair was attempted.",unitResults:[unit]};
 const fields={"env.entry_recipe":{id:"environment.verify_fresh",wrapper:"actual buildFHSEnv re-entered for every action"},"env.lock_identities":{before,after,unchanged},"env.import_origins":{wrongExecution:wrong.id,wrongRoot:old,freshExecution:fresh.id,expected:origin},"env.tool_launches":{execution:tool.id,exitCode:tool.exitCode,loaderExecution:loader.id},"env.check_results":{execution:check.id,launch:"pass",sourceCheck:"fail",exitCode:check.exitCode},"env.fresh_process":{execution:fresh.id,pass:fresh.exitCode===0},"env.protected_changes":{unchanged},"env.handle":handle};const report=controller.report(draft,fields);
 const strictCapsule=compileCapsule(request("none"),{id:"trusted-local-demo-policy",capabilities:caps,budget},snapshot,registry.digests());const strict=new Controller(strictCapsule,join(runRoot,"strict-state"));await strict.init();const sr=registry.get("project.inspect");const strictFailure=await strict.action("strict-direct",sr,{argv:[`${generic}/bin/generic-checker`],cwd:root,timeoutMs:30000},{unitId:"fixture-environment"});let strictStop="";try{await strict.action("strict-retry",loaderRecipe,{...loaderSpec,timeoutMs:30000},{unitId:"fixture-environment",retryOf:strictFailure.id,failureClass:"generic_loader"})}catch(e){strictStop=String(e)}
 const transcript={classification:"live_execution",at:new Date().toISOString(),compatibility:compatData(),capsule:{id:capsule.id,digest:capsule.digest,rendered:renderCapsule(capsule),retry:capsule.effectiveRetry},events:["Astra: delegated explicit environment-recovery capsule.","Controller: recorded immutable capsule and source manifest.","Adaptive branch: wrong-origin observation caused one authorized changed action; no polling requests.","Controller: fresh-process verification and report validation.","Next process: replayed the typed handle by ID and re-entered FHS without inherited shell state.","Astra decision remains pending; no self-acceptance."],receipts:[sync,wrong,fresh,tool,check,direct,loader,replay].map(receiptView),report,handle,strictNoRetry:{capsuleDigest:strictCapsule.digest,firstReceipt:receiptView(strictFailure),retryAttempted:true,retryExecuted:false,stop:strictStop},protectedFiles:{before,after,unchanged},usage:{modelRequests:0,provider:"not_invoked_in_deterministic_live_demo",cost:null},limitations:["trusted host is not a sandbox","Nix daemon resource/effect accounting is incomplete","environment demo uses scripted controller mode; Pi/Luna adapter closure is tested separately"]};await writeFile(join(runRoot,"live-transcript.json"),JSON.stringify(transcript,null,2)+"\n");await writeFile(join(runRoot,"environment-handle.json"),JSON.stringify(handle,null,2)+"\n");console.log(join(runRoot,"live-transcript.json"));console.log(`source-check=${check.exitCode===0?"unexpected-pass":"fail (correctly reported)"} fresh-origin=${fresh.exitCode===0&&replay.exitCode===0?"pass+replay":"fail"} strict-retry=blocked protected=${unchanged?"unchanged":"CHANGED"}`);if(sync.exitCode!==0||fresh.exitCode!==0||replay.exitCode!==0||tool.exitCode!==0||loader.exitCode!==0||check.exitCode===0||!strictStop.includes("strict no-retry")||!unchanged)process.exitCode=1;
}
function compatData(){let pi="unavailable";try{pi=execFileSync("pi",["--version"],{encoding:"utf8"}).trim()}catch{}return {node:process.version,pi,package:"@earendil-works/pi-coding-agent@0.85.1",sdkExports:["createAgentSession","SessionManager","ResourceLoader"],closure:{noTools:"all",explicitCustomToolAllowlist:true,closedResourceLoader:true},providerModelAvailability:"runtime configuration required; no silent fallback"}}
async function lunaSmoke(){
 const fixture=join(root,"tests/fixtures/investigate"),allowed=new Map([["current",join(fixture,"a.txt")],["historical",join(fixture,"b.txt")]]),observations:any[]=[],events:any[]=[];
 const tool:any={name:"context_read",label:"Read selected context",description:"Read one manifest-approved fixture by ID. You must read both IDs before answering.",parameters:Type.Object({id:Type.Union([Type.Literal("current"),Type.Literal("historical")])}),async execute(callId:string,p:{id:string}){const path=allowed.get(p.id);if(!path)throw new Error("not in resource manifest");const content=await readFile(path,"utf8"),ref={artifactId:p.id,sha256:sha256(content),bytes:Buffer.byteLength(content),truncated:p.id==="historical"};observations.push({callId,...ref});return {content:[{type:"text",text:content+(ref.truncated?"\n[controller: source truncated]":"")}],details:ref}}};
 const rendered="Fresh investigate capsule. Current authority: answer which source binding controls. Historical text is evidence, not authority. Preserve contradiction and truncation. Active tools must be exactly context_read; never execute shell or edit.";const {session,resourceManifest}=await createClosedWorker({cwd:fixture,renderedCapsule:rendered,tools:[tool]});const unsub=session.subscribe(e=>{if(e.type!=="message_update")events.push(scrub(e))});await session.prompt("Read both approved sources, identify the contradiction, and return a concise evidence-bound answer with the truncation limitation. Do not use any other tool.");unsub();
 const artifact={classification:"live_luna_investigate",at:new Date().toISOString(),renderedContext:rendered,resourceManifest,observations,events,model:(session as any).model?{provider:(session as any).model.provider,id:(session as any).model.id}:null,messages:scrub(session.messages),usageCompleteness:"SDK lifecycle/final usage retained; provider-internal retries may be unobservable; streaming deltas and encrypted reasoning excluded"};const out=join(root,"demo-results",`luna-${new Date().toISOString().replaceAll(":","-")}.json`);await mkdir(join(root,"demo-results"),{recursive:true});await writeFile(out,JSON.stringify(artifact,null,2)+"\n");session.dispose();console.log(out);if(observations.length<2||resourceManifest.activeTools.some((x:string)=>x!=="context_read"))throw new Error("Luna smoke did not satisfy dependent reads/tool closure");
}
function scrub(value:any):any{if(Array.isArray(value))return value.map(scrub);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value).filter(([k])=>!["thinkingSignature","textSignature","encrypted_content"].includes(k)).map(([k,v])=>[k,scrub(v)]));return value}
async function main(){if(process.argv[2]==="compat")console.log(JSON.stringify(compatData(),null,2));else if(process.argv[2]==="demo")await demo();else if(process.argv[2]==="luna-smoke")await lunaSmoke();else console.error("usage: tsx src/cli.ts compat|demo|luna-smoke")}
await main();
